version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: user_app_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: user_app
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database-mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  # Laravel Backend
  backend:
    build:
      context: ./backend-laravel
      dockerfile: Dockerfile
    container_name: user_app_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: user_app
      DB_USERNAME: laravel
      DB_PASSWORD: 
      APP_KEY: 
      JWT_SECRET: 
    depends_on:
      - db
    volumes:
      - ./backend-laravel:/var/www/html
    networks:
      - app_network

  # React Frontend
  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: user_app_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge